sudo: false
language: python
cache:
    - pip
    - directories:
        - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/
        - /home/travis/virtualenv/python2.7.9/bin/
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script: make all && python -c 'import functions'

